
/* Retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.
*/

SELECT c.name AS category_name, SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items AS oi
JOIN products AS p ON oi.product_id = p.id
JOIN categories AS c ON p.category_id = c.id
GROUP BY c.id
ORDER BY total_revenue DESC;